---
output: pdf_document
geometry: "margin=2.5cm"
header-includes:
  - \usepackage{fancyhdr}
  - \fancyfoot{}

---
\pagestyle{fancy}
\fancyhead[R]{Kendra Wyant \thepage}
\fancyhead[L]{}

# Personal Statement

I have always been a data person, though I didn’t always know it. When I was nine years old, I called it "spy club." I started a club with my younger sister and cousin and assigned us all "spy homework," where we wrote down everything we observed our family members doing. I remember crouching behind the couch, staring at my dog, and jotting down, "5 p.m. - still sleeping." Looking back, I had no idea at the time that this was data collection, or what data could be used for, but I knew I enjoyed it. This curiosity about observing patterns to understand behavior has carried through every stage of my life.

When I took my first Research Methods in Psychology course, I felt like I had finally been given the words for what I had been doing all along. My "spy homework" was now called systematic observation. Concepts from experimental design and statistics provided me with tools to make sense of the data I collected, and I became excited by the idea that human behavior could be studied with both curiosity and precision.

As a therapist, I routinely collect data in and between sessions to collaboratively assess, adapt, and tailor treatment to my clients. During my practicum placement in the PTSD clinic at the Madison VA, data were critical. My patients completed weekly symptom inventories prior to sessions, and those scores often prompted discussions that increased their awareness of therapeutic barriers (e.g., probing issues of avoidance when PTSD scores remained high). Daily exposure homework assignments, where patients recorded subjective units of distress, proved to be a powerful tool in therapy sessions. In many cases, patients did not realize the level of functional improvement they were experiencing until they saw their habituation visually depicted in their data.

Much like the curiosity that began with my childhood "spy club," I have developed a strong clinical interest in assessment.  I enjoy the mystery of collecting and integrating data from clinical interviews, life circumstances, and cognitive and personality measures to solve a person’s presenting problem. It seems fitting, then, that my first clinical supervisor gave me the nickname "Detective Wyant" for my ability to ask probing questions, uncover diagnostic information, and conceptualize my clients' presentations. 

My appreciation for data has also translated into a passion for research. I chose to study substance use disorders early in my academic career, but it was not until I began focusing on predicting lapses back to substance use that I fully appreciated how challenging it is to capture the highly individualized and dynamic nature of lapses through traditional data collection methods. I have become excited about exploring large datasets collected from smartphones, like geolocation, cellular communications, and brief daily self-report data, that can be combined with machine learning methods to make accurate and timely predictions. These approaches can enable low-burden, continuous monitoring of symptoms and deliver interventions at moments of high risk, before a lapse occurs.

While my "spy club" days are behind me, my detective skills remain active in my clinical and research work. I am proud to call myself a clinical scientist, and I am eager to continue developing my assessment and intervention skills during internship. Most of all, I look forward to continuing to use data, not just to understand, but to meaningfully support people struggling with mental health challenges.

{{< pagebreak >}}

# Theoretical Orientation Statement

My clinical training has been grounded in a cognitive-behavioral framework. Consistent with my scientist-practitioner training, I prioritize evidenced-based practice. This means selecting empirically supported treatments and using objective symptom measures, along with my clinical "detective skills", to collect data that inform individualized treatment. I strive to tailor conceptualizations to each patient's unique context, taking into account personality, cultural, and environmental factors, preferences, and comorbid conditions. I view presenting problems as interactions among thoughts, emotions, and behaviors and use present-focused active approaches to improve psychological symptoms. The specific interventions I select are personalized to the patient. 

Although I identify primarily as a cognitive-behavioral therapist, I find it valuable to draw from other empirically supported approaches to enhance treatment fit. For example, I often integrate principles of Motivational Interviewing (MI) to encourage behavioral change while maintaining a collaborative and nonjudgmental stance. I have successfully used MI to promote discussion, awareness, and change in areas of sleep, eating, alcohol use, and therapy-interfering behaviors. Similarly, I frequently incorporate skills training drawn from Dialectical Behavior Therapy and Skills Training in Affective Interpersonal Regulation to help patients develop mindfulness, emotion regulation, and interpersonal effectiveness.

As a clinician, I approach my patients with curiosity and humility. I encourage collaboration in treatment planning and regularly solicit feedback, both in session and through the delivery of measurement-based care. I believe that personalizing treatment to clients’ preferences, needs, and stage of readiness requires ongoing reassessment. At times, patient feedback has led to meaningful shifts in our therapeutic direction. 

One case that illustrates my theoretical orientation involved a 36-year-old multiracial single mother of two who presented with anxiety and compulsive "doomsday prepping" behaviors. Together, we conceptualized her anxiety about safety as being temporarily relieved, but ultimately reinforced, by these behaviors. Our CBT treatment plan focused on tracking behaviors (e.g., what a typical day looks like for her, how much time and at what times does she engage in prepping), identifying anxiety triggers (such as watching the news or "doom scrolling" on social media), and implementing behavioral changes (e.g., setting limits on her social media intake). In areas where she expressed resistance, such as limiting phone use before bed to improve sleep hygiene, MI techniques helped us explore her ambivalence and readiness to change. As her symptoms improved via outcome measures such as the Outcome Questionnaire 45.2 and General Anxiety Disorder - 7, we examined the cognitions still driving her anxiety and recognized that many were tied to real-world stressors, including job insecurity and a racially charged political climate. Acknowledging that some of her fears were grounded in reality, we collaboratively shifted our focus toward developing emotion regulation and coping skills. By the end of treatment, her anxiety had meaningfully decreased, and she demonstrated greater engagement in her daily life and parenting roles.


{{< pagebreak >}}

# Diversity Statement

While data play a large role in my case conceptualizations, I have learned that they do not always fit the person in front of me. I have become especially mindful of this when working with individuals from diverse cultural backgrounds. A truly individualized conceptualization of a patient's presenting concerns requires the careful integration of their unique sociocultural context and lived experience. In these cases, I draw on my clinical detective skills and lead with curiosity and humility.

One particularly vulnerable group that has shaped my integrative approach is justice-involved individuals. In one case, I conducted an assessment for a 30-year-old Black man who had been incarcerated since the age of 18. Despite repeated requests for help, he received no consistent mental health treatment. I was brought in by his lawyer, who suspected he had a serious mental illness. In preparation for my interview with him, I reviewed over ten years of prison records. The picture they painted was grim. He had a history of substance use prior to incarceration, and prison mental health providers had described him as "drug seeking" and "malingering."

However, the data did not neatly fit together to support these claims. In his requests made to prison staff and letters to family members, I saw signs of confusion and disorganization. Thus, I approached my clinical interview with curiosity and without judgment, offering empathy and validation while also asking difficult questions. His reaction, like others I have witnessed in similar settings, reminded me that meaningful therapeutic impact can occur even in brief clinical encounters when space is made for it. My conceptualization of this man revealed a very different story from what his chart suggested. He met diagnostic criteria for schizophrenia and had likely been experiencing symptoms since the beginning of his incarceration. Unfortunately, biases reflected in previous providers' notes prevented him from receiving appropriate care.

My clinical work has also enabled me to reflect on my own positionality when working with patients from diverse backgrounds. This became particularly apparent when working with Veterans using Prolonged Exposure therapy. My first patient was a 35-year-old male combat Veteran with PTSD and alcohol use disorder. During our first imaginal exposure session, he reported experiencing maximum distress (100/100 SUDS) that persisted for 20 minutes. I sat listening as he sweated, shook, and struggled to breathe. I left the session shaken, worried that I might have pushed him too far since his life experiences were so different from my own. I consulted with my supervisor who explained that his response was consistent of Veterans with severe PTSD and avoidant coping, and that continuing with this treatment was his best option for symptom relief. This experience made me realize how confronting my own discomfort in session can help me to take a step back and examine the differences between myself and clients, and in doing so refines my conceptualizations of each of them.

I also carry these lessons into my research. Predictive models that perform well only for majority groups may exacerbate existing disparities in access to care and clinical outcomes. To address this, I have helped develop analyses that use multicultural and diversity variables to evaluate model fairness and ensure that the clinical utility of my work extends to underserved and minority populations.

{{< pagebreak >}}

# Research Statement

My program of research aims to improve continuing care for substance use disorders by automating the delivery of personalized, adaptive recovery support. Substance use disorders are chronic conditions characterized by high relapse rates, substantial co-occurrence with other physical and mental health problems, and an increased risk of mortality. Continuing care involves ongoing monitoring, tailored adjustments to lifestyle and behavior over time, and, when necessary, re-engagement with more intensive treatment. This is the gold standard for managing chronic conditions such as diabetes, hypertension, and asthma. Yet, our current system for treating substance use disorders lacks the capacity for long-term, clinician-delivered care. As a result, individuals are often left to determine on their own, "How can I best support my recovery today?"

This is a difficult question, given that the risk factors precipitating lapses are highly individualized, numerous, dynamic, and interactive. The optimal supports to address these risks vary both across individuals and within an individual over time. Therefore, effective interventions must be personalized to both the person and the moment to meet the complex and changing needs of individuals in recovery. Achieving this level of personalization requires access to a high-dimensional array of likely risk factors measured over time, a predictive model capable of handling complex, non-linear relationships between features and lapse, and tools from interpretable AI to understand the putative contributors to risk. My research demonstrates the feasibility of integrating these three components. 

Smartphone sensing of self-report and passive sensor data enables frequent, longitudinal measurement of proximal risk factors necessary for temporally precise lapse risk prediction. In two mixed-methods studies, I found that individuals with alcohol (Wyant et al., 2023) and opioid (Wyant et al., in prep) use disorders were both willing and able to adhere to various sensing methods, including sensing of self-report, geolocation, and cellular communication data. Across these methods, I have trained machine learning models that predict immediate (i.e., within the next day) and future (i.e., within the next two weeks) lapses with excellent performance (Wyant & Sant’Ana et al., 2024; Wyant et al., under review, Wyant et al., in prep). Past use (i.e., lapses), craving, and abstinence self-efficacy have consistently emerged as the most important predictors of lapse on average across participants. However, other predictors, such as time spent in risky locations and affect, emerge as important features for some individuals at some moments in time, highlighting the need for high-dimensional risk measurement. Importantly, the features contributing to lapse risk are interpretable targets for intervention. I am currently working to demonstrate how the key contributors to daily risk predictions can be mapped onto Cognitive Behavioral Therapy and MATRIX relapse prevention tools to generate daily, risk-relevant recovery activity recommendations aligned with evidenced-based care (Wyant et al., in press). 

Ultimately, I aim to make ongoing treatment and support for substance use disorders more accessible.  Automated daily support messages tailored to the individual have the potential to prevent imminent lapses and sustain long-term recovery by delivering data-driven, personalized recommendations equitably at a scalable level. 