---
title: Clinical Psychology Portfolio
author:
  - name: Kendra Wyant 
    affiliations:
      - Department of Psychology, University of Wisconsin-Madison
date: last-modified
number-sections: true 
editor_options: 
  chunk_output_type: console
---

## Background


### Personal Statement 

Students should provide a brief (up to approximately 500 words) personal statement.  This statement should include a narrative of their career goals to provide a context for the materials provided in their portfolio.  The statement can also provide details regarding current accomplishments and expertise, anticipated accomplishments and/or expertise to be gained in the program and plans to acquire it, obstacles experienced or anticipated, or any other relevant information to contextualize their portfolio or establish themselves as an emerging clinical scientist.



### Supporting documents 
- [Current CV](https://arc.psych.wisc.edu/wp-content/uploads/sites/425/2020/08/Kendra_Wyant_CV.pdf)
- [Unofficial transcript](https://github.com/KendraPaquette/portfolio/blob/main/documents/transcript_kw.pdf)


## Research Experiences

### Research Statement 
Research statement: Provide in format of tenure portfolio research statement or internship research statement (i.e., Please describe your research experience and interests in 500 words).  See appendix on writing a research statement at the end of this document for more details.

### First-Author Publications 

1. **Wyant, K.**, Sant’Ana, S.J., Fronk, G.E., & Curtin, J.J. (in press). Machine learning models for temporally precise lapse prediction in alcohol use disorder. *Journal of Psychopathology and Clinical Science*. [preprint](https://osf.io/preprints/psyarxiv/cgsf7)    

Abstract: We developed three separate models that provide hour-by-hour probabilities of a future lapse back to alcohol use with increasing temporal precision (i.e., lapses in the next week, next day, and next hour). Model features were based on raw scores and longitudinal change in theoretically implicated risk factors collected through ecological momentary assessment (EMA). Participants (*N*=151; 51% male; mean age = 41; 87% White, 97% Non-Hispanic) in early recovery (1–8 weeks of abstinence) from alcohol use disorder provided 4x daily EMA for up to three months. We used grouped, nested cross-validation, with 1 repeat of 10-fold cross-validation for the inner loop and 3 repeats of 10-fold cross-validation for the outer loop to train models, select best models, and evaluate those best models on auROC. Models yielded median areas under the receiver operating curves (auROCs) of .90, .91, and .94 in the 30 held-out test sets for week, day, and hour level models, respectively. Some feature categories consistently emerged as being globally important to lapse prediction across our week, day, and hour level models (i.e., past use, future efficacy). However, most of the more punctuate, time varying constructs (e.g., craving, past stressful events, arousal) appear to have greater impact within the next hour prediction model. This research represents an important step toward the development of a smart (machine learning guided) sensing system that can both identify periods of peak lapse risk and recommend specific supports to address factors contributing to this risk.  

Relative contributions:   
- conceptualization - 25%   
- design - 25%  
- analysis - 50%; Collaborated with John Curtin to develop generic functions and supporting code for creating features, running main and baseline models on CHTC, and running parameterized scripts to get model performance metrics.  
- writing - 30%; Contributed to original draft, edits, and revisions per reviewer suggestions.


2. **Wyant, K.**, Moshontz, H., Ward, S.B., Fronk, G.E., & Curtin, J.J. (2023). Acceptability of personal sensing among people with alcohol use disorder: Observational study. *JMIR mHealth and uHealth*. [http://dx.doi.org/10.2196/41833](http://dx.doi.org/10.2196/41833)  

Abstract: Personal sensing may improve digital therapeutics for mental health care by facilitating early screening, symptom monitoring, risk prediction, and personalized/adaptive interventions. However, further development and use of personal sensing requires better understanding of its acceptability to people targeted for these mental health applications. We assessed the acceptability of active and passive personal sensing methods in a sample of people with moderate to severe alcohol use disorder (AUD) using both behavioral and self-report measures.  This sample was recruited as part of a larger grant-funded project to develop a temporally precise machine learning algorithm to predict lapses. Participants (*N*=154; 50% female; mean age = 41; 87% White, 97% Non-Hispanic) in early recovery (1–8 weeks of abstinence) were recruited to participate in a 3-month longitudinal study. Participants were modestly compensated to engage with active (4x daily ecological momentary assessment; EMA, audio check-in, and sleep quality) and passive (geolocation, cellular communication logs, and text message content) sensing methods that were selected to tap into constructs from Marlatt's Relapse Prevention model. We assessed 3 behavioral indicators of acceptability: participants’ choices about their participation in the study at various stages in the procedure, their choice to opt-in to provide data for each sensing method, and their adherence to a subset of the active methods (EMA, audio check-in). We also assessed 3 self-report measures of acceptability (interference, dislike, and willingness to use for 1 year) for each method. *N*=191 of 192 eligible participants consented to personal sensing. Most of these individuals (88%) also returned 1 week later to formally enroll and begin to provide these data. All participants (100%) opted-in to provide data for EMA, sleep quality, most passive methods (geolocation, cellular communication logs), with 1 participant not providing text message content. Three participants (2%) did not provide any audio check-ins. The average completion rate for all EMAs was 80% and 94% for 1x daily. The completion rate for the daily audio check-in was 54%. Aggregate participant ratings indicated all personal sensing methods to be significantly more acceptable (all *p* < .05) compared to neutral across subjective measures of interference, dislike, and willingness to use for 1 year. Participants did not significantly differ in their dislike of active compared to passive methods (*p* = .23). However, participants reported a higher willingness to use passive (vs. active) methods for 1 year (*p* = .04). These results suggest that active and passive sensing methods are acceptable to people with AUD over a longer period than has previously been assessed.  This was true even for data streams that contained potentially more sensitive information (e.g., geolocation, cellular communications).  Important individual differences were observed both across people and methods, which indicate opportunities for future improvements.  
  

Relative contributions:   
- conceptualization - 50%   
- design - 50%  
- analysis - 80%; Performed all analyses under supervision of John Curtin.    
- writing - 60%; Primary contributor to original draft, edits, and revisions per reviewer suggestions.  


### Co-Author Publications 

Moshontz, H., Colmenares, A.J., Fronk, G.E., Sant’Ana, S.J., **Wyant, K.**, Wanta, S.E., … & Curtin, J.J. (2021). Prospective prediction of lapses in opioid use disorder: Protocol for a personal sensing study. *Journal of Medical Internet Research: Research Protocols.* [https://doi.org/10.2196/29563](https://doi.org/10.2196/29563)   

Relative contributions   
- conceptualization - 10%   
- design - 10%  
- analysis - NA  
- writing - 10%    


### Presentations 

1. **Wyant, K.**, Sant’Ana, S.J., Fronk, G.E., & Curtin, J.J. (2024, June). *Using ecological momentary assessment for temporally precise lapse prediction in alcohol use disorder*. Flash talk presented at the 2024 Society for Ambulatory Assessment Conference, Ann Arbor, MI. 

Abstract: Ecological momentary assessment (EMA) can support frequent, in-situ, longitudinal measurement necessary for monitoring relapse risk. This study evaluates whether EMA can be used to build machine learning models that predict hour-by-hour probabilities of future alcohol lapses with increasing temporal precision (in the next week, next day, and next hour). Model features were engineered from raw scores and longitudinal change in responses to 4X daily EMAs from participants (*N*=151; 51% male; mean age = 41; 87% White, 97% Non-Hispanic) in early recovery from alcohol use disorder for up to three months. We used grouped, nested cross-validation to select and evaluate the performance of our best models. Models yielded median areas under the receiver operating curves of .89, .90, and .93 in held-out test sets for week, day, and hour level models, respectively. This confirms EMA can be used to predict alcohol lapses with high sensitivity and specificity for new individuals.  

Slides available [here](https://github.com/KendraPaquette/portfolio/blob/main/presentations/saa_flashtalk_2024_0604.pdf)   


2. **Wyant, K.** (2024, April). *Precision mental health for substance use disorders using personal sensing.* Capstone Presentation at the 2024 UW-Madison Clinical Psychology Research Symposium, Madison, WI.   

Abstract:  

Slides available [here](https://github.com/KendraPaquette/portfolio/blob/main/presentations/capstone_2024_0426.pdf)   

3. **Wyant, K.** & Curtin, J.J. (2023, August). *Using high-throughput computing to predict future lapses back to alcohol use.* Presented at the Open Science Grid School HTC Showcase, Madison, WI.   

Abstract:   

Slides available [here](https://github.com/KendraPaquette/portfolio/blob/main/presentations/chtc_2023_0808.pdf)   

4. **Wyant, K.**, Moshontz, H., Ward, S.B., Fronk, G.E., & Curtin, J.J. (2023, March). *Acceptability of personal sensing among people with alcohol use disorder.* Presented at Collaborative Perspectives on Addiction Annual Meeting, Albuquerque, NM.  

Abstract: Personal sensing may improve digital therapeutics for mental health care. However, further development and use of personal sensing first requires better understanding of its acceptability to people targeted for these mental health applications. Participants (*N*=154; 50% female; mean age=41; 87% White, 97% Non-Hispanic) in early recovery from alcohol use disorder were recruited from the Madison, WI area. Participants engaged with active (EMA, audio check-in, and sleep quality) and passive (geolocation, cellular communication logs, and text message content) personal sensing methods for up to three months. We assessed the acceptability of these methods using both behavioral and self-report measures. The average completion rate for all requested EMAs was 81%. The completion rate for the audio check-in was 55%. Aggregate participant ratings indicated all methods to be significantly more acceptable (all *P*’s < .05) compared to neutral across subjective measures of interference, dislike, and willingness to use for one year. Participants did not significantly differ in their dislike of active compared to passive methods (*P* = .23). However, participants reported a higher willingness to use passive methods for one year compared to active methods (P = .04). These results suggest both active and passive personal sensing methods are generally acceptable to people with alcohol use disorder. Important individual differences were observed both across people and methods which indicate opportunities for future improvements.  

Poster available [here](https://github.com/KendraPaquette/portfolio/blob/main/presentations/CPA_2023_0316.pdf)   


5. **Wyant, K.** & Curtin, J.J. (2021, December). *Personal sensing of smartphone communications to support recovery from alcohol use disorder.* Presented at the 36th Annual First Year Project Symposium, Madison, WI.   

Abstract:  



Slides available [here](https://github.com/KendraPaquette/portfolio/blob/main/presentations/fyp_symposium.pdf)



6. **Wyant, K.** & Curtin, J.J. (2021, August). *A personal sensing approach to alcohol lapse prediction.* Presented at the 2021 Psychology Research Experience Program Symposium, Madison, WI. 

Abstract: Alcohol use disorder is a chronic relapsing disease. People can relapse days, weeks, months, or even years after achieving abstinence. Identifying when an initial lapse will occur is an important goal in preventing lapses, repeated lapses, and relapse. Because of the dynamic nature of lapse risk, traditional treatment, like monthly therapy or biweekly therapy sessions, may not be best suited for monitoring lapse risk and intervening prior to relapse, or a full return to previous drinking behavior. Personal sensing methods offer a tool for capturing fluctuations in lapse risk in real time. One understudied personal sensing method in the substance use literature is cellular communication logs. The present study contextualizes participants’ communications with self-report information about their frequently communicated with contacts and seeks to develop a predictive model to predict when someone is at a high risk of lapsing.  

Slides available [here](https://github.com/KendraPaquette/portfolio/blob/main/presentations/prep_2021_0804.pdf)



7. **Wyant, K.** & Curtin, J.J. (2021, April). *Personal sensing in clinical research.* Presented at the UW-Madison clinical psychology departmental weekly lunch and learn (virtual).

Abstract: Personal sensing is a longitudinal method for in situ data collection. Raw personal sensing data streams (e.g., sensor or log data) can be used to create measures that act as indicators of mental health constructs. Thus, paving the way for more accessible and timely treatment and intervention options. However, using personal sensing in clinical settings requires that people accept their use and will sustain the behaviors they require. This presentation provides an overview of the acceptability of various personal sensing data streams individually and in the same context among participants with alcohol use disorder. Future implications of the acceptability of these measures will be discussed in the context of my First Year Project.   

Slides available [here](https://github.com/KendraPaquette/portfolio/blob/main/presentations/lunch_and_learn_2021_0407.pdf)  


### Workshops Led

1. Introduction to Regularization   
Organization: LUCID, UW-Madison  
Date: June 30, 2021  
Description: Led workshop on applying regularization to the linear model in the tidymodels framework.  
Materials available [here](https://github.com/KendraPaquette/intro_to_regularization)  
 

### Workshops and Trainings Attended

1. AI and Society Seminar  
Instructors:  Tim Rogers, Ph.D., and Caitlin Roa, Ph.D.     
Dates: September 8, 2021 - May 6, 2022  
Description: Interdisciplinary weekly seminar to discuss and apply machine learning and AI concepts.   

2. Introduction to Structural Equation Modeling Workshop   
Instructors: Daniel Bauer, Ph.D. & Patrick Curran, Ph.D.  
Dates: May 10 – 12, 2021  
Description: An introductory three-day workshop on the application and interpretation of path analysis, confirmatory factor analysis, and structural equation models with latent variables.   

3. LUCID Training Seminar     
Instructors:  Tim Rogers, Ph.D., and Caitlin Roa, Ph.D.   
Dates: September 2, 2020 - April 30, 2021    
Description: Interdisciplinary weekly seminar to work on and discuss scientific communication skills and applications of machine learning.   
 


## Clinical Experiences

### Clinical Orientation Statement 

Internship clinical orientation statement: Please describe your theoretical orientation and how this influences your approach to case conceptualization and intervention. You may use de-identified case material to illustrate your points if you choose. 500 word limit


### Practicum Experiences 

Descriptions of clinical practicum experiences: Brief description should include the name and dates for the practicum, brief description of the client population and other relevant details (e.g., interventions, modalities). This should include documentation of clinical hours (per internship categories) and available/completed supervisor evaluations.

### Certification by Clinical Director  

Certification of clinical competencies can be found [here](https://github.com/KendraPaquette/portfolio/blob/main/documents/Certificate%20of%20Completion%20of%20Phase%20I%20Clinical%20Training%20-%20Kendra%20Wyant.pdf)


### Assessment Report Samples 

Provide integrative or other assessment reports after appropriate de-identification. Do not include raw data from assessments.


## Diversity Experiences

### Diversity Statement 
- notes:  

Diversity in clients (children and juveniles in need of protective services, work with Legal Assistance to Incarcerated People, college undergraduates at UHS, and a mix of students and community members in PRTC, additionally, next year I will be working in the VA PTSD clinic to gain exposure to VA culture)

Diversity in research - careful consideration given to how to interpret our models and results as regard to representation of sample and how to go beyond this to get qualitative and quantitative data that is representative in regards to race, SES, geographic location. (PREP project?)

### Workshops 

Empowering people to break the bias habit: Evidenced-based approaches to reducing bias and creating inclusion
Speaker: Will Cox, Ph.D.
Description: 3-hour workshop to introduce academic audiences to the concepts of implicit or unconscious biases and assumptions about diverse groups of people by treating the application of such biases as a “habit.” Participants will uncover their own biases, discover the underlying concepts and language used in the psychological and social psychological literature to describe such processes, participate in interactive discussions about the potential influence of implicit or unconscious bias in their department/unit, and learn evidence-based strategies for reducing the application of these biases.


### Mentorship and Service 

1.	Maximizing Access to Research Careers Alumni Mentor Program
Date: Fall 2020 – Spring 2022
Mentee: Christopher Creighton, CSUF – Fullerton, CA

2.	PREP Alumni Mentor Program
Date: Summer 2021
Mentee: Olivia Sutton, Westminster College – Salt Lake City, UT

3. Clinical Area Antiracism and Academic Training Committee Member
Date: Fall 2020 – Spring 2021

4. PREP Research Mentor, includes summer DELTA training - a copy of the syllabus can be found [here](https://github.com/KendraPaquette/portfolio/blob/main/documents/PREP_mentor_syllabus_2024.pdf).




## Teaching Experiences

- guest lecture
- led lecture discussion on explanatory methods in IAML, co-led weekly lab
- materials for GLM
- Grading papers and open ended exams and providing feedback on writing for 2 classes since 2021

Course evaluations for IAML can be found [here](https://github.com/KendraPaquette/portfolio/blob/main/documents/iaml_ta_2024.pdf)





