---
output: pdf_document
geometry: "margin=2.75cm"
---


October 31, 2025

Dear Dr. Newsom and the Selection Committee,

I am pleased to submit my application for the VA Los Angeles Ambulatory Care Center Internship Program. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice. 

My research program demonstrates that smartphone sensing data and machine learning can be used to automate the delivery of personalized recovery support messages to prevent lapse and relapse. Through this work, I have become well-versed in evidence-based treatments, including CBT, Relapse Prevention, and the MATRIX model. While my research has provided a strong foundation in substance use interventions, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, a primary training goal for my internship year is to gain in-depth experience providing substance use treatment and working with individuals in higher levels of care, such as intensive outpatient programs. I am particularly excited about the **Substance Use Disorders Clinic** rotation, as it aligns closely with these goals. I look forward to gaining experience delivering evidenced-based substance use treatment and collaborating with a multidisciplinary team. 

A second goal is to further develop my assessment skills. I am excited that a **Neuropsychological Assessment** rotation may be available. Currently, I am completing an assessment-focused practicum at Mendota Mental Health Institute, a forensic state hospital, where I have gained experience assessing and diagnosing neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I look forward to continuing advanced assessment training.

My work at Mendota Mental Health Institute has given me experience working with individuals with severe psychosis and other serious mental illnesses. This role emphasized the importance of nuanced case conceptualization and individualized interventions, as well as the challenges inherent in treating patients with severe mental illness, such as limited or unreliable psychosocial histories, poor insight, and co-occurring legal, medical, and housing concerns. During my internship, I hope to further develop my skills in assessing and treating patients with severe mental illness and complex, comorbid diagnostic profiles. Consequently, I am particularly interested in the **Psychosocial Rehabilitation and Recovery Center** rotation.

I am also interested in learning to apply evidence-based approaches through brief, time-limited encounters with patients in primary care settings through the **Primary Care-Mental Health Integration** rotation. During my practicum at the Madison VA Medical Center, I observed the profound impact that just five sessions of Written Exposure Therapy can have in reducing PTSD symptoms. Delivering these interventions efficiently in non-specialty settings is especially powerful, as it expands access to gold-standard treatments.

Several additional aspects of the VA Los Angeles Ambulatory Care Center Internship Program make it an ideal fit for my training goals. First, developing cultural competence is a key objective for me during internship. My practicum experiences have been limited to the Madison, WI area, and I am eager to work with clients from more diverse backgrounds and intersectional identities. Training in a region as culturally diverse as Los Angeles would provide invaluable opportunities to strengthen my competence in serving diverse and underserved populations.

Second, I was pleased to see that research is an elective component of the program. I am particularly enthusiastic about the opportunity to collaborate with VA researchers on ongoing projects or conduct secondary data analyses. Consistent with the scientist-practitioner model, I value the reciprocal relationship between clinical application and research, as each informs and strengthens the other.

Finally, I hope to gain additional experience working within a multidisciplinary team and collaborating closely with psychiatrists, nurses, social workers, and medical providers. My practicum experiences have taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans.

The VA Los Angeles Ambulatory Care Center Internship Program’s emphasis on evidence-based treatment and their commitment to culturally responsive care strongly aligns with my professional values and goals. My practicum experience at the Madison VA reinforced that additional training in a VA setting is an ideal fit as I continue to develop as a clinical scientist. During my time there, I observed how the VA seamlessly integrates science and practice. Moreover, Veterans represent a population disproportionately affected by substance use disorders, making the VA a particularly high-impact setting for my future career aspirations. On a personal note, I was born and raised in Southern California and would be excited to return to the area and be closer to loved ones. Thank you for considering my application and for the opportunity to pursue further clinical training.



\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
