---
output: pdf_document
geometry: "margin=2.75cm"
---


November 1, 2025

Dear Dr. Joshua Morrison and the Selection Committee,

I am pleased to submit my application for the California Psychology Internship Consortium at **Alvarado Parkway Institute Behavioral Health System**. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice. 

My research program demonstrates that smartphone sensing data and machine learning can be used to automate the delivery of personalized recovery support messages to prevent lapse and relapse. Through this work, I have become well-versed in evidence-based treatments, including CBT, Relapse Prevention, and the MATRIX model. While my research has provided a strong foundation in substance use interventions, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, a primary training goal for my internship year is to gain in-depth experience providing substance use treatment. I am particularly excited about the opportunity to gain experience in both inpatient and intensive outpatient treatment settings. I look forward to delivering evidence-based treatments in group and individual formats and for patients pursuing a range of recovery goals, including abstinence and harm reduction.

My work at Mendota Mental Health Institute, a forensic state hospital, has given me experience working with individuals with severe psychosis and other serious mental illnesses. I have gained experience assessing and diagnosing neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I have learned the importance of nuanced case conceptualization and individualized interventions, as well as the challenges inherent in treating patients with severe mental illness, such as limited or unreliable psychosocial histories, poor insight, and co-occurring legal, medical, and housing concerns. Experience in inpatient or outpatient rotations that primarily treat severe and persistent mental illness would be valuable for further developing my skills in assessing and treating patients with severe mental illness and complex, comorbid diagnostic profiles.

Given the high comorbidity between trauma exposure and substance use disorders, it is important to me to continue developing my skills in trauma-focused care. During my practicum placement in the PTSD Clinic at the Madison VA Medical Center, I discovered how much I enjoyed providing trauma treatment. I received extensive training in Cognitive Processing Therapy and Prolonged Exposure, and I resonated with the structured nature of these interventions and the clear outcome measures that track treatment progress. I am eager to strengthen these skills, learn to deliver other trauma-focused interventions, and gain experience assessing and treating more complex presentations of PTSD.

Several additional aspects of Alvarado Parkway Institute Behavioral Health System and the California Psychology Internship Consortium make it an ideal fit for my training goals. First, developing cultural competence is a key objective for me during internship. My practicum experiences have been limited to the Madison, WI area, and I am eager to work with clients from more diverse backgrounds and intersectional identities. Training in a region as culturally diverse as San Diego would provide invaluable opportunities to strengthen my competence in serving diverse and underserved populations and in adapting interventions to each patient’s cultural context. Similarly, I would be interested in working with forensic populations, as I have greatly enjoyed treating and assessing this population at Mendota Mental Health Institute.

Second, I was excited to learn that there was an Assessment rotation. Assessment has been a priority for me across all of my practicum experiences, and I look forward to continuing advanced assessment training and participating in related didactics. 

Third, I have found that I enjoy working in hospital settings with patients on residential units. I am particularly drawn to the multidisciplinary team approach and the opportunity to collaborate closely with psychiatrists, nurses, social workers, and medical providers. Working within these teams have taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans. Consequently, I was excited to see that all rotations include time devoted for inpatient care.

Finally, I am drawn to the program’s emphasis on third-wave cognitive behavioral therapies and am excited by the opportunity to learn to effectively deliver evidence-based interventions that focus on promoting acceptance and psychological flexibility, such as Acceptance and Commitment Therapy, Dialectical Behavior Therapy, and Mindfulness-Based Cognitive Therapy.

Alvarado Parkway Institute Behavioral Health System’s focus on evidence-based treatment and its commitment to culturally responsive care strongly aligns with my professional values and goals. My practicum experiences have reinforced that additional training in a hospital setting is an ideal fit as I continue to develop as a clinical scientist. On a personal note, I was born and raised in Southern California and would be excited to return to the area and be closer to loved ones. Thank you for the opportunity to apply for further clinical training, and thank you for your consideration.


\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  


{{< pagebreak >}}

November 1, 2025

Dear Dr. Susan Rindt and the Selection Committee,

I am pleased to submit my application for the California Psychology Internship Consortium at **Aurora Behavioral Healthcare/San Diego**. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice. 

My research program demonstrates that smartphone sensing data and machine learning can be used to automate the delivery of personalized recovery support messages to prevent lapse and relapse. Through this work, I have become well-versed in evidence-based treatments, including CBT, Relapse Prevention, and the MATRIX model. While my research has provided a strong foundation in substance use interventions, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, a primary training goal for my internship year is to gain in-depth experience providing substance use treatment. Given the large population of people with substance use disorders at Aurora Behavioral Healthcare/San Diego, this program would provide a valubale training opportunity. I look forward to delivering evidence-based treatments in group and individual formats and for patients pursuing a range of recovery goals, including abstinence and harm reduction.

My work at Mendota Mental Health Institute, a forensic state hospital, has given me experience working with individuals with severe psychosis and other serious mental illnesses. I have gained experience assessing and diagnosing neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I have learned the importance of nuanced case conceptualization and individualized interventions, as well as the challenges inherent in treating patients with severe mental illness, such as limited or unreliable psychosocial histories, poor insight, and co-occurring legal, medical, and housing concerns. Inpatient experience where severe and persistent mental illness are primarily treated would be valuable for further developing my skills in assessing and treating patients with severe mental illness and complex, comorbid diagnostic profiles.

Given the high comorbidity between trauma exposure and substance use disorders, it is important to me to continue developing my skills in trauma-focused care. During my practicum placement in the PTSD Clinic at the Madison VA Medical Center, I discovered how much I enjoyed providing trauma treatment. I received extensive training in Cognitive Processing Therapy and Prolonged Exposure, and I resonated with the structured nature of these interventions and the clear outcome measures that track treatment progress. I am eager to strengthen these skills, learn to deliver other trauma-focused interventions, such as EMDR, and gain experience assessing and treating more complex presentations of PTSD.

Several additional aspects of Aurora Behavioral Healthcare/San Diego and the California Psychology Internship Consortium make it an ideal fit for my training goals. First, developing cultural competence is a key objective for me during internship. My practicum experiences have been limited to the Madison, WI area, and I am eager to work with clients from more diverse backgrounds and intersectional identities. Training in a region as culturally diverse as San Diego would provide invaluable opportunities to strengthen my competence in serving diverse and underserved populations and in adapting interventions to each patient’s cultural context. 

Second, I was excited to learn that there was a large emphasis on assessment experiences. Assessment has been a priority for me across all of my practicum experiences, and I look forward to continuing advanced assessment training and participating in related didactics. 

Third, I have found that I enjoy working in hospital settings with patients on residential units. I am particularly drawn to the multidisciplinary team approach and the opportunity to collaborate closely with psychiatrists, nurses, social workers, and medical providers. Working within these teams have taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans. Consequently, I was excited to see that all rotations include time devoted for inpatient care.

Finally, I am drawn to the program’s emphasis on third-wave cognitive behavioral therapies and am excited by the opportunity to learn to effectively deliver evidence-based interventions that focus on promoting acceptance and psychological flexibility, such as Acceptance and Commitment Therapy and Dialectical Behavior Therapy. I was also intrigued to learn that the Yalom inpatient model for groups is taught. I resonated with this approach during didactics in undergrad and I would love to receive clinical training in this area.

Aurora Behavioral Healthcare/San Diego’s focus on evidence-based treatment and its commitment to culturally responsive care strongly aligns with my professional values and goals. My practicum experiences have reinforced that additional training in a hospital setting is an ideal fit as I continue to develop as a clinical scientist. On a personal note, I was born and raised in Southern California and would be excited to return to the area and be closer to loved ones. Thank you for the opportunity to apply for further clinical training, and thank you for your consideration.


\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
