---
output: pdf_document
geometry: "margin=2.75cm"
---


October 31, 2025

Dear Dr. Christina Wierenga, Dr. Elizabeth Wrape, and the Selection Committee,

I am pleased to submit my application for the UCSD/VA Psychology Internship Training Program. I am specifically applying to:

1.	**Position 3**: VA PTSD Clinical Team, VA Alcohol and Drug Treatment Program 
2.	**Position 4**: VA PTSD Clinical Team, Dual Diagnosis Recovery Program 
3.	**Position 5**: VA Substance Abuse Rehabilitation and Recovery Treatment Program, VA Behavioral Health Interdisciplinary Program

I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice. My research program demonstrates that smartphone sensing data and machine learning can be used to automate the delivery of personalized recovery support messages to prevent lapse and relapse. Through this work, I have become well-versed in evidence-based treatments, including CBT, Relapse Prevention, and the MATRIX model.

While my research has provided a strong foundation in substance use interventions, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, a primary training goal for my internship year is to gain in-depth experience providing substance use treatment and working with individuals in higher levels of care, such as residential and intensive outpatient programs. I am particularly excited about the **Alcohol and Drug Treatment Program**, **Dual Diagnosis Recovery Program**, and **Substance Abuse Rehabilitation and Recovery Treatment Program** rotations, as they align closely with these goals. I look forward to gaining experience delivering evidenced-based substance use treatments, engaging in the harm reduction program, and participating in the weekly SUD didactic. 

Given the high comorbidity between trauma experiences and substance use disorders, it is important to me to continue developing my skills in trauma-focused care. During my practicum placement in the PTSD Clinic at the Madison VA Medical Center, I realized how much I enjoyed providing trauma treatment. I received extensive training in Cognitive Processing Therapy and Prolonged Exposure, and I resonated with the structured nature of these interventions and the clear outcome measures that track treatment progress. This work also highlighted the importance of nuanced case conceptualization and tailored interventions for Veterans with trauma and co-occurring mental health concerns. I am eager to strengthen these skills through the **PTSD Clinical Team**, **Substance Abuse Rehabilitation and Recovery Treatment Program**, and **Behavioral Health Interdisciplinary Program** rotations and gain experience in assessing and treating more complex presentations of PTSD. 

In addition to my specialized training goals, I also hope to increase the breadth of my clinical experiences during internship. Consequently, I am interested in getting experience in the **Behavioral Health Interdisciplinary Program** rotation. Specifically, I look forward to working with Veterans presenting with a wide range of concerns and varying levels of impairment. This opportunity will provide foundational training that I can apply in any future setting. I am particularly interested in working with diverse clinical presentations, collaborating within interdisciplinary teams, further developing my competence in delivering evidence-based treatments such as ACT and DBT, and learning to culturally adapt interventions to align with each Veteran’s unique cultural context.

Several additional aspects of the UCSD/VA Psychology Internship Training Program make it an ideal fit for my training goals. First, developing cultural competence is a key objective for me during internship. My practicum experiences have been limited to the Madison, WI area, and I am eager to work with clients from more diverse backgrounds and intersectional identities. Training in a region as culturally diverse as San Diego would provide invaluable opportunities to strengthen my competence in serving diverse and underserved populations.

Second, I was pleased to see that research is an integral component of the program. I am enthusiastic about the opportunity to collaborate with VA and UCSD researchers on ongoing projects or conduct secondary data analyses. Consistent with the scientist-practitioner model, I value the reciprocal relationship between clinical application and research, as each informs and strengthens the other.

Finally, I hope to gain additional experience working within a multidisciplinary team and collaborating closely with psychiatrists, nurses, social workers, and medical providers. My practicum experiences have taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans.

The UCSD/VA Psychology Internship Training Program’s emphasis on evidence-based treatment and their commitment to culturally responsive care strongly aligns with my professional values and goals. My practicum experience at the Madison VA reinforced that additional training in a VA setting is an ideal fit as I continue to develop as a clinical scientist. During my time there, I observed how the VA seamlessly integrates science and practice. Moreover, Veterans represent a population disproportionately affected by substance use disorders, making the VA a particularly high-impact setting for my future career aspirations. On a personal note, I was born and raised in Southern California and would be excited to return to the area and be closer to loved ones. Thank you for considering my application and for the opportunity to pursue further clinical training.


\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
