---
output: pdf_document
geometry: "margin=2.75cm"
---


October 31, 2025

Dear Dr. Farina and the Selection Committee,

I am pleased to submit my application for the VA Long Beach Healthcare System Internship Program, **General Track**. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by the APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice. Consistent with the scientist-practitioner model, I value the reciprocal relationship between clinical application and research, as each informs and strengthens the other. I believe I will be most successful in an academic medical setting. During my practicum at the Madison VA Medical Center, I observed how the VA seamlessly integrates science and practice. Moreover, Veterans represent a population disproportionately affected by substance use disorders, making the VA a particularly high-impact setting for this work. For these reasons, I believe this program would be instrumental in helping me achieve my career aspirations. Below, I outline my training goals for the internship year and how this program aligns with them. 

My research program demonstrates that smartphone sensing data and machine learning can be used to automate the delivery of personalized recovery support messages to prevent lapse and relapse. Through this work, I have become well-versed in evidence-based treatments, including CBT, Relapse Prevention, and the MATRIX model. While my research has provided a strong foundation in substance use interventions, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, a primary training goal for my internship year is to gain in-depth experience providing substance use treatment and working with individuals in higher levels of care, such as intensive outpatient programs. I am particularly excited about the **Addiction and Recovery Treatment Program** rotation, as it aligns closely with these goals. I look forward to gaining experience delivering evidenced-based substance use treatment in group and individual formats and collaborating with a multidisciplinary team. 

My practicum placement at Mendota Mental Health Institute, a state forensic hospital, has provided me experience with individuals with severe psychosis and other serious mental illnesses. This role emphasized the importance of nuanced case conceptualization and individualized interventions, as well as the challenges inherent in treating patients with severe mental illness, such as limited or unreliable psychosocial histories, poor insight, and co-occurring legal, medical, and housing concerns. During my internship, I hope to further develop my skills in assessing and treating patients with severe mental illness and complex, comorbid diagnostic profiles. Consequently, I am particularly interested in the **Pathways to Recovery Center** rotation.

Given the high comorbidity between trauma experiences and substance use disorders, it is important to me to continue developing my skills in trauma-focused care. During my practicum placement in the PTSD Clinic at the Madison VA Medical Center, I realized how much I enjoyed providing trauma treatment. I received extensive training in Cognitive Processing Therapy and Prolonged Exposure, and I resonated with the structured nature of these interventions and the clear outcome measures that track treatment progress. I am eager to strengthen these skills through the **PTSD Clinical Team** rotation and gain experience in assessing and treating more complex presentations of PTSD.

I appreciate the generalist training model of the program. One of my training goals for internship is to increase the breadth of my clinical experiences. Consequently, I am eager to get experience in the **Outpatient Mental Health: Community Based Outpatient Clinics** rotation. Specifically, I look forward to working with Veterans presenting with a wide range of concerns and varying levels of impairment. This opportunity will provide foundational training that I can apply in any future setting. I am particularly interested in working with diverse clinical presentations, collaborating within interdisciplinary teams, further developing my competence in delivering evidence-based treatments such as ACT and DBT, and learning to culturally adapt interventions to align with each Veteran’s unique cultural context.

Several additional aspects of the VA Long Beach Healthcare System Internship Program make it an ideal fit for my training goals. First, developing cultural competence is a key objective for me during internship. My practicum experiences have been limited to the Madison, WI area, and I am eager to work with clients from more diverse backgrounds and intersectional identities. Training in a region as culturally diverse as Long Beach would provide invaluable opportunities to strengthen my competence in serving diverse and underserved populations.

Second, I hope to gain additional experience working within a multidisciplinary team and collaborating closely with psychiatrists, nurses, social workers, and medical providers. My practicum experiences have taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans.

Third, I am eager to further develop my assessment skills during internship. Assessment has been a consistent priority across my practicum experiences. For example, I am currently completing an assessment-focused practicum at Mendota Mental Health Institute, where I have gained experience assessing and diagnosing neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I look forward to continuing advanced assessment training through didactics and comprehensive assessment cases.

The VA Long Beach Healthcare System Internship Program’s focus on evidence-based treatment and its commitment to culturally responsive care strongly aligns with my professional values and goals. My practicum experiences have reinforced that additional training in a VA medical setting is an ideal fit as I continue to develop as a clinical scientist. On a personal note, I was born and raised in Southern California and would be excited to return to the area and be closer to loved ones. Thank you for considering my application and for the opportunity to pursue further clinical training.



\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
