---
output: pdf_document
geometry: "margin=2.75cm"
---


November 1, 2025

Dear Dr. Bohlig and the Selection Committee,

I am pleased to submit my application for the Madison VA Hospital and Clinics Psychology Doctoral Internship Program, **General Track**. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice. 

My research program demonstrates that smartphone sensing data and machine learning can be used to automate the delivery of personalized recovery support messages to prevent lapse and relapse. Through this work, I have become well-versed in evidence-based treatments, including CBT, Relapse Prevention, and the MATRIX model. While my research has provided a strong foundation in substance use interventions, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, a primary training goal for my internship year is to gain in-depth experience providing substance use treatment and working with individuals in higher levels of care, such as intensive outpatient programs. I am particularly excited about the **Dual-Diagnosis Rotation - Addictive and Substance Use Disorders Treatment Program** rotation, as it aligns closely with these goals. I look forward to gaining experience delivering evidenced-based substance use treatment and collaborating with a multidisciplinary team. 

Given the high comorbidity between trauma experiences and substance use disorders, it is important to me to continue developing my skills in trauma-focused care. During my practicum placement in the PTSD Clinical Team at the Madison VA, I realized how much I enjoyed providing trauma treatment. I received extensive training in Cognitive Processing Therapy and Prolonged Exposure, and I resonated with the structured nature of these interventions and the clear outcome measures that track treatment progress. This work also highlighted the importance of nuanced case conceptualization and tailored interventions for Veterans with trauma and co-occurring mental health concerns. I am eager to strengthen these skills through the **PTSD Clinical Team** rotation and gain experience in assessing and treating more complex presentations of PTSD. 

I appreciate the generalist training model at the Madison VA. One of my training goals for internship is to increase the breadth of my clinical experiences. Consequently, I am eager to get experience in the **Mental Health Clinic** rotation. Specifically, I look forward to working with Veterans presenting with a wide range of concerns and varying levels of impairment. This opportunity will provide foundational training that I can apply in any future setting. I am particularly interested in working with diverse clinical presentations, collaborating within interdisciplinary teams, further developing my competence in delivering evidence-based treatments such as ACT and DBT, and learning to culturally adapt interventions to align with each Veteran’s unique cultural context.

I am also interested in learning to apply evidence-based approaches through brief, time-limited encounters with patients in primary care settings through the **Primary Care Mental Health Integration** rotation. During my practicum at the Madison VA, I observed the profound impact that just five sessions of Written Exposure Therapy can have in reducing PTSD symptoms. Delivering these interventions efficiently in non-specialty settings is especially powerful, as it expands access to gold-standard treatments.

Another training goal is to further develop my assessment skills. I am excited to see that assessment is integrated into several of the rotations. I am also very interested in the opportunity to gain neuropsychology testing experience through the **Geriatric Research, Education, and Clinical Center Memory Assessment Clinic** rotation. Currently, I am completing an assessment-focused practicum at Mendota Mental Health Institute, a forensic state hospital, where I frequently assess and diagnose neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I look forward to continuing advanced assessment training and participating in related didactics.

I was pleased to see that research is an integral component of the program. I am particularly enthusiastic about the opportunity to work with a research mentor and carry out an independent research project. Consistent with the scientist-practitioner model, I value the reciprocal relationship between clinical application and research, as each informs and strengthens the other. 

The Madison VA Hospital and Clinics Psychology Doctoral Internship Program’s emphasis on evidence-based treatment and their commitment to culturally responsive care strongly aligns with my professional values and goals. My practicum experience at the Madison VA reinforced that additional training in a VA setting is an ideal fit as I continue to develop as a clinical scientist. During my time there, I observed how the VA seamlessly integrates science and practice. Moreover, Veterans represent a population disproportionately affected by substance use disorders, making the VA a particularly high-impact setting for my future career aspirations. On a personal note, I greatly enjoyed the people I met and the training experiences I received during my practicum, and I would be excited to rejoin the team.

Thank you for considering my application and for the opportunity to pursue further clinical training.




\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
