---
output: pdf_document
geometry: "margin=2.75cm"
---


November 2, 2025

Dear Dr. Gust-Brey and the Selection Committee,

I am pleased to submit my application for the Mendota Mental Health Institute Psychology Internship Program. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice.  

My current practicum experience on the East Admission Medical Unit at Mendota Mental Health Institute has provided me with valuable experience working with individuals with severe psychosis and other serious mental illnesses. This experience has highlighted the complexity of treating patients with limited or unreliable psychosocial histories, poor insight, and co-occurring legal and medical concerns. I have also deepened my understanding of complex clinical presentations through my practicum placement in the PTSD Clinic at the Madison VA Medical Center, where I discovered how much I enjoy providing trauma treatment. I received extensive training in Cognitive Processing Therapy and Prolonged Exposure and found that I resonated with the structured nature of these interventions and the clear outcome measures used to track treatment progress. Together, these experiences have emphasized the importance of nuanced case conceptualization and the challenges inherent in treating patients with severe mental illness. During internship, I hope to further develop my skills in assessing and treating individuals with severe mental illness and complex, comorbid diagnostic profiles through the various **Forensic Unit** rotations available.

Another training goal for internship is to further develop my assessment skills. I am excited that assessment is an integral part of each rotation. Assessment has been a consistent priority across my practicum experiences. For example, I am currently completing an assessment-focused practicum at Mendota Mental Health Institute, where I have gained experience assessing and diagnosing neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I look forward to continuing advanced assessment training and attending weekly assessment seminars. Consequently, I am particularly interested in the **Risk Assessment** rotation where I could learn to deliver new assessment protocols, such as the PCL-R and VRS:SO. 

Additionally, through my practicum experiences, I have found that I enjoy working in hospital settings with patients on residential units. I have especially appreciated the multidisciplinary team approach at Mendota Mental Health Institute, and I am excited about the opportunity to continue collaborating closely with psychiatrists, nurses, social workers, and medical providers. Working within these teams has taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans.

Finally, through my research, I have become well-versed in evidence-based substance use treatments, including CBT, Relapse Prevention, and the MATRIX model. However, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, one of my training goals for internship is to gain experience providing substance use treatment. I am particularly excited about the **Substance Use Disorder Program** supplementary rotation, as it closely aligns with this goal. I look forward to delivering evidence-based treatments in both group and individual formats.

The Mendota Mental Health Institute Psychology Internship Program’s emphasis on assessment and its commitment to culturally responsive care strongly align with my professional values and goals. My previous practicum experiences have reinforced that additional training in a hospital setting is an ideal fit as I continue to develop as a clinical scientist. Moreover, forensic settings represent a population disproportionately affected by substance use disorders, making Mendota Mental Health Institute a particularly high-impact setting for my future career aspirations. On a personal note, I have greatly enjoyed the people I have met and the training experiences I have received during my practicum, and I would be excited to remain on the team. Thank you for considering my application and for the opportunity to pursue further clinical training.


\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
