---
output: pdf_document
geometry: "margin=2.75cm"
---


November 2, 2025

Dear Dr. Kafka and the Selection Committee,

I am pleased to submit my application for the DSH-Metropolitan Clinical Psychology Doctoral Internship Program, **General Track**. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice.  Given the high comorbidity of substance use with severe mental illness, trauma, and incarceration, I believe this program offers an ideal training environment to help me achieve my professional goals of integrating research and practice.

My work on a maximum-security forensic intake unit at Mendota Mental Health Institute has given me experience working with individuals with severe psychosis and other serious mental illnesses. This experience has highlighted the complexity of treating patients with limited or unreliable psychosocial histories, poor insight, and co-occurring legal and medical concerns. I further deepened my understanding of complex clinical presentations during my practicum placement in the PTSD Clinic at the Madison VA Medical Center, where I discovered how much I enjoy providing trauma treatment. I received extensive training in Cognitive Processing Therapy and Prolonged Exposure, and I resonated with the structured nature of these interventions and the clear outcome measures that track treatment progress. Together, these experiences have emphasized the importance of nuanced case conceptualization and the challenges inherent in treating patients with severe mental illness. During internship, I hope to further develop my skills in assessing patients with severe mental illness and complex, comorbid diagnostic profiles through the **Forensic Unit** rotation. Additionally, given my interest in substance use disorders I would be excited to facilitate relapse prevention groups on the unit. 

Another training goal for internship is to further develop my assessment skills. I am excited that an **Advanced Cognitive Assessment** rotation is available. Assessment has been a consistent priority across my practicum experiences. For example, I am currently completing an assessment-focused practicum at Mendota Mental Health Institute where I have gained experience assessing and diagnosing neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I look forward to continuing advanced assessment training and attending weekly assessment seminars.

Several additional aspects of the DSH-Metropolitan Clinical Psychology Doctoral Internship Program make it an ideal fit for my training goals. First, developing cultural competence is a key objective for me during internship. My practicum experiences have been limited to the Madison, WI area, and I am eager to work with clients from more diverse backgrounds and intersectional identities. Training in a region as culturally diverse as Los Angeles would provide invaluable opportunities to strengthen my competence in serving diverse and underserved populations.

Second, I hope to gain additional experience working within a multidisciplinary team and collaborating closely with psychiatrists, nurses, social workers, and medical providers. My practicum experiences have taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans.

Finally, I was pleased to see that research is incorporated into the program didactics. Consistent with the scientist-practitioner model, I value the reciprocal relationship between clinical application and research, as each informs and strengthens the other. I am particularly enthusiastic about the opportunity to develop an independent project to improve patient care at DSH-Metropolitan. 

The DSH-Metropolitan Clinical Psychology Doctoral Internship Program’s emphasis on assessment and their commitment to culturally responsive care strongly aligns with my professional values and goals. My previous practicum experiences have reinforced that additional training in a hospital setting is an ideal fit as I continue to develop as a clinical scientist. Moreover, forensic settings represent a population disproportionately affected by substance use disorders, making DSH-Metropolitan a particularly high-impact setting for my future career aspirations. On a personal note, I was born and raised in Southern California and would be excited to return to the area and be closer to loved ones. Thank you for considering my application and for the opportunity to pursue further clinical training.



\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
