---
output: pdf_document
geometry: "margin=2.75cm"
---


November 2, 2025

Dear Dr. Henry and the Selection Committee,

I am pleased to submit my application for the Pacific Clinics Psychology Internship Program, **Adult Outpatient Track**. I am a sixth-year doctoral student in the Clinical Psychology program at the University of Wisconsin–Madison, which is dually accredited by APA and PCSAS. My career goal is to work as a clinical scientist focused on improving substance use treatments through both research and practice. 

My research program demonstrates that smartphone sensing data and machine learning can be used to automate the delivery of personalized recovery support messages to prevent lapse and relapse. Through this work, I have become well-versed in evidence-based treatments, including CBT, Relapse Prevention, and the MATRIX model. While my research has provided a strong foundation in substance use interventions, my clinical practicum experiences in this area have been more limited. They have primarily involved brief psychoeducational and Motivational Interviewing sessions with college students, as well as trauma-focused treatment for Veterans with co-occurring substance use disorders. Therefore, a primary training goal for my internship year is to gain experience providing substance use treatment to individuals with and without co-occuring mental health issues. 

My work at Mendota Mental Health Institute, a forensic state hospital, has given me experience working with individuals with severe psychosis and other serious mental illnesses. This role emphasized the importance of nuanced case conceptualization and individualized interventions, as well as the challenges inherent in treating patients with severe mental illness, such as limited or unreliable psychosocial histories, poor insight, and co-occurring legal, medical, and housing concerns. During my internship, I hope to further develop my skills in assessing and treating patients with severe mental illness and complex, comorbid diagnostic profiles. I would be particularly interested in a secondary placement at **Passageways** to learn further address the unique needs of people with severe mental illness.

I also appreciate the generalist training model of the program. One of my training goals for internship is to increase the breadth of my clinical experiences. I am looking forward to working with clients presenting with a wide range of concerns at varying levels of impairment. This opportunity will provide foundational training that I can apply in any future setting. Furthermore, my previous practicum experiences have been in hospital and academic medical settings. I am eager to gain experience in a community outpatient setting where I can work with clients with diverse clinical presentations, further develop my competence in delivering evidence-based treatments in individual and group format, and learn to culturally adapt interventions to align with each client’s unique cultural context.

Several additional aspects of the Pacific Clinics Psychology Internship Program make it an ideal fit for my training goals. First, developing cultural competence is a key objective for me during internship. My practicum experiences have been limited to the Madison, WI area, and I am eager to work with clients from more diverse backgrounds and intersectional identities. Training in a region as culturally diverse as Los Angeles would provide invaluable opportunities to strengthen my competence in serving diverse and underserved populations.

Second, I am eager to further develop my assessment skills during internship. Assessment has been a consistent priority across my practicum experiences. For example, I am currently completing an assessment-focused practicum at Mendota Mental Health Institute, where I have gained experience assessing and diagnosing neurocognitive disorders, learning disorders, and severe psychopathology, including schizophrenia spectrum disorders. I look forward to the opportunity to potentially participate in an **Assessment** focused secondary placement or to receive advanced training within the Adult Outpatient Clinic.

Third, I hope to gain additional experience working within a multidisciplinary team and collaborating closely with psychiatrists, nurses, social workers, medical providers, and peer partners. My practicum experiences have taught me the value of integrating diverse professional perspectives to develop cohesive, patient-centered care plans.

The Pacific Clinics Psychology Internship Program’s emphasis on evidence-based treatment and their commitment to culturally responsive care strongly aligns with my professional values and goals. The presentations of severe mental illness and substance use disorders typically seen at the Adult Outpatient Clinic fit with my clinical interests, and the community-based setting would increase depth of my experiences as a developing clinician. On a personal note, I was born and raised in Southern California and would be excited to return to the area and be closer to loved ones. Thank you for considering my application and for the opportunity to pursue further clinical training.



\

Sincerely,  

Kendra Wyant, M.S.  
Clinical Psychology Ph.D. Candidate  
University of Wisconsin-Madison  
Pronouns: she/her/hers  
